### ISSUE TITLE
array_interleave incorrect tests

### ISSUE THREAD

**Issue by gregoryvit** [Hexlet/battle_asserts#232]
В задаче написано:
> "... Arrays can be of different lengths, so if one arrays ends before the other, just continue adding elements from the remaining array"

Пример не соответствует заданию:
> "Example: [5,"4",1,"9"] == solution([5,1,3], ["4","9"])"

Тест видимо проверяет такой же вариант:
```
F
======================================================================
FAIL: test_solution (__main__.TestSolution)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "checker.py", line 15, in test_solution
    self.assertEqual(expected, solution.solution(*arguments), msg)
AssertionError: Lists differ: [4, 2, -4, 2] != [4, 2, -4, 2, -2, 3]

Second list contains 2 additional elements.
First extra element 4:
-2

- [4, 2, -4, 2]
+ [4, 2, -4, 2, -2, 3]
?             +++++++
 : Arguments was: [[4, -4], [2, 2, -2, 3]]
```

или вот:
```
F
======================================================================
FAIL: test_solution (__main__.TestSolution)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "checker.py", line 15, in test_solution
    self.assertEqual(expected, solution.solution(*arguments), msg)
AssertionError: Lists differ: [] != [1]

Second list contains 1 additional elements.
First extra element 0:
1

- []
+ [1]
?  +
 : Arguments was: [[], [1]]
```

Исходный код:
```python
def solution(first_array, second_array):
  result_array = first_array
  for i, item in enumerate(second_array):
    if i < len(first_array):
      result_array.insert(2 * i + 1, item)
    else:
      result_array.append(item)
  return result_array
```

**Comment by mokevnin** [comment]
Спасибо за репорт. Описание задачи поправили.
